### ISSUE TITLE
Cookiecutter Support 

### ISSUE THREAD

**Issue by avelino** [rochacbruno/python-project-template#1]
https://cookiecutter.readthedocs.io/

**Comment by rochacbruno** [comment]
I appreciate the idea, but this template is a Github template not a general purpose.

The idea is.

## HOW TO USE THIS TEMPLATE

1. Click on 'Use this template' or go to rochacbruno/python-project-template/generate
2. Wait until the first run of CI finishes (Github Actions will process the template and commit to your new repo)

The Github Actions will do the `cookiecutter` work and will replace the template naming, after the first run on originated repo the project is good to go with the new information.
