### ISSUE TITLE
add pre-commit config that ensures black/linting

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [rochacbruno/python-project-template#3]
as pre-commit ties the linting/type checking up nicely,
it would be a most fabulous addition to the listing/tooling

**Comment by rochacbruno** [comment]
Closing, reason here: https://github.com/rochacbruno/python-project-template/blob/main/ABOUT_THIS_TEMPLATE.md#why-this-template-is-not-using-pre-commit- 

Thanks
